### ISSUE TITLE
When downloading database zip the file is of a db version of EPiServer 7017

### ISSUE THREAD

**Issue by jacobkhan** [OXXAS/CommerceStarterKit#36]
when downloading the zip database the db has not been upgraded to the latest version yet.

**Comment by evest** [comment]
Sorry, it was, but in a separate branch for the language change. Fixed it now in https://github.com/OXXAS/CommerceStarterKit-Database/commit/4e1be0ad8edf04c2be36f1fd135cf6aa9c8eb846
