### ISSUE TITLE
Build fails when having spaces in your directory

### ISSUE THREAD

**Issue by dstomphorst** [OXXAS/CommerceStarterKit#38]
The build fails when you have spaces in your path.The post build event WarmUp.exe will fail
Surrounding the post build stap with quotes solves this issue.

**Old:**
$(ProjectDir)WarmMeUp\WarmMeUp.exe http://localhost:49883/

**New:**
**"**$(ProjectDir)WarmMeUp\WarmMeUp.exe**"** http://localhost:49883/

**Comment by evest** [comment]
Will be fixed here to when the fork is merged back.
